### ISSUE TITLE
No extension description in found in archive error

### ISSUE THREAD

**Issue by starcraft086** [KitwareMedical/SlicerLookingGlass#20]
Hi,
I keep getting this message when trying to add your extension to slicer3d. Could you please tell me how to proceed?

<img width="491" alt="Screenshot 2022-03-13 at 21 32 48" src="https://user-images.githubusercontent.com/88210971/158080140-0fab334c-827d-4441-83b6-562be22d8e9c.png">

For reference I am on MacOS Monterrey, using an M1 chip and Slicer 4.11

Many thanks

**Comment by jcfr** [comment]
Thanks for the report.

Based on the screenshot, it seems that you downloaded the source by clicking on "Download Zip" directly available in the GitHub interface.

Since the extension is expected to be available through the [extension manager](https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html), could you download a recent version of Slicer available at https://download.slicer.org and try again.

If you still have issues, consider opening a new  issue.
